version: '3.8'

services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    restart: unless-stopped
    ports:
      - "9042:9042"   # Porta CQL para conexão com clientes
      - "9160:9160"   # Porta Thrift (opcional, para compatibilidade)
    volumes:
      - scylla-data:/var/lib/scylla
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql
    environment:
      - SCYLLA_CLUSTER_NAME=local-cluster
      - SCYLLA_AUTO_BOOTSTRAP=false
      - SCYLLA_STARTUP_OPTIONS=--smp 1 --memory 512M
      - DEVELOPER_MODE=true

  # script de inicialização
  scylla-init:
    image: scylladb/scylla:latest
    depends_on:
      - scylla
    entrypoint: [ "/bin/sh", "-c", "sleep 20 && cqlsh scylla -f /docker-entrypoint-initdb.d/init.cql" ]
    volumes:
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

volumes:
  scylla-data:
    driver: local
