spring:
  application:
    name: todo-list

  cassandra:
    keyspace-name: todolist
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

